seed: 42
num_workers : 4

model_name    : 'sgaligner'
modules       : ['point', 'gat', 'rel', ''] # ['point', 'gat', 'rel']
use_predicted : True
registration  : True

data :
  name            : Scan3R
  root_dir        : /home/main/workspace/k2room1/sgaligner/3RScan/data/3RScan/data/3RScan/
  label_file_name : labels.instances.align.annotated.v2.ply
  pred_subfix     : inseg.ply

preprocess :
  pc_resolutions      : [512]
  subscenes_per_scene : 7
  filter_segment_size : 512
  min_obj_points      : 50
  anchor_type_name    : ''

model :
  rel_dim             : 9
  attr_dim            : 164
  alignment_thresh    : 0.4

val : 
  batch_size          : 4

reg_model :
  K : 2